#version: '3.1'
services:
  mongo:
    image: mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - "mongo"
    ports:
      - 8081:8081
