name: resources_api
description: A sample command-line application.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shelf: ^1.1.4
  mongo_dart: ^0.7.0+2
  shelf_router: ^1.0.0
  dart_jsonwebtoken: ^2.3.0
  envify: ^2.0.0
  crypto: ^3.0.1
  redis_dart: ^0.1.0+4
  uuid: ^3.0.4
  http: ^0.13.4
  encrypt: ^5.0.1
  http_parser: ^4.0.0
  mime: ^1.0.1
  chunked_stream: ^1.4.1
  dartssh2: ^2.4.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  envify_generator: ^2.0.0
  build_runner: ^2.0.4
